name: psx
description: "A simple password management application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_ui_auth: ^1.15.0
  firebase_ui_oauth_google: ^1.3.3
  fluttertoast: ^8.2.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  provider: ^6.0.0
  google_sign_in: ^6.2.1
  path: ^1.9.0
  flutter_dotenv: any
  sqflite_sqlcipher: 3.1.0+1
  sqflite: ^2.3.3+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - .env