name: psx
description: "A simple password management application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  firebase_ui_auth: ^1.14.0
  firebase_ui_oauth_google: ^1.3.2
  fluttertoast: ^8.2.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  provider: ^6.0.0
  google_sign_in: ^6.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
  - assets/